openapi: 3.0.1
info:
  title: Book Shop
  description: Book GET API.
  version: 1.0.0
servers:
  - url: /v2
paths:
  /book:
    get:
      summary: Get Books
      operationId: getBooks
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Le Rouge et le Noir
        author:
          type: string
          example: Stendhal
